# Generated by Django 4.1 on 2022-09-01 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
            preserve_default=False,
        ),
    ]
